document.writeln("    <div class=\'b\'>");
document.writeln("        <div class=\'b1\'>");
document.writeln("            <div class=\'b2\'><img src=\'./img/touxiang.jpg\' /></div>");
document.writeln("            <p class=\'b3\'>KAI<span>′S</span>博客</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'b4\'>");
document.writeln("            <p>人生,</p>");
document.writeln("            <p>就像一盒巧克力,</p>");
document.writeln("            <p>你永远不知道下一块会是什么味道!</p>");
document.writeln("            <p>—— —— 《阿甘正传》</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'c\'>");
document.writeln("        <div class=\'c1\'><a href=\'file:///D:/KAIPersonalblog/index.html\'>首页</a></div>");
document.writeln("        <div class=\'c1\'><a href=\'\'>个人日记</a></div>");
document.writeln("        <div class=\'c1\'><a href=\'\'>软件大全</a></div>");
document.writeln("        <div class=\'c1\'><a href=\'\'>视频电影</a></div>");
document.writeln("        <div class=\'c1\'><a href=\'\'>留言板</a></div>");
document.writeln("    </div>");